### ISSUE TITLE
_ADAPTER_OBJECT is empty

### ISSUE THREAD

**Issue by SergiusTheBest** [RevJay/vergilius-project#9]
However it the raw data it's not:
```
    name: _ADAPTER_OBJECT
    id: 1339
    kind: STRUCT
    sizeof: 640
    data:
      -
        name: AdapterObject
        id: 1340
        offset: 0
        ordinal: 0
```
